### ISSUE TITLE
npm run browser-tests leads to module not found error

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-testing-helpers#3]
I'm trying to get started with `sw-testing-helpers` for a new project. The [README](https://github.com/GoogleChrome/sw-testing-helpers/blob/master/README.md) says that I can use `npm run browser-tests` to run the placeholder browser tests, but doing that leads to:

```sh
[~/git/sw-testing-helpers]$ npm run browser-tests

> sw-testing-helpers@0.0.5 browser-tests /Users/jeffy/git/sw-testing-helpers
> nodemon test/server/index.js

28 Mar 11:54:54 - [nodemon] 1.7.1
28 Mar 11:54:54 - [nodemon] to restart at any time, enter `rs`
28 Mar 11:54:54 - [nodemon] watching: *.*
28 Mar 11:54:54 - [nodemon] starting `node test/server/index.js ./src/node-helpers/index.js`
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/jeffy/git/sw-testing-helpers/test/server/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
28 Mar 11:54:54 - [nodemon] app crashed - waiting for file changes before starting...
```

What commands do run to execute an initial placeholder browser test suite, that I could then modify to suit my testing needs?

**Comment by gauntface** [comment]
Propel is the only repo using this at the moment so is the only one I can recommend looking at for example. It's vacation today in UK so can put together some proper getting started comments tomorrow

**Comment by gauntface** [comment]
Obviously feel free to add comments or raise a PR to help make is all clearer.

**Comment by gauntface** [comment]
@jeffposnick I've done a fairly hefty refactor / reorg of the code to help with this.

Checkout the readme and the docs: https://googlechrome.github.io/sw-testing-helpers/

If you hit issues please either re-open or open new issues to highlight problem errors. Obviously PR's also welcome if you want to fix stuff yourself :)
