### ISSUE TITLE
activateSW should wait for iframe to be controlled by SW

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-testing-helpers#35]
Try running this:

console.log('iframe sw => ', iframe.contentWindow.navigator.serviceWorker.getRegistration().then(reg => console.log(reg)));

If shouldn't be undefined

**Comment by jeffposnick** [comment]
This was an issue with the `<platinum-sw>` tests, too. See https://github.com/PolymerElements/platinum-sw/blob/master/test/controlled-promise.js for the workaround I used.

**Comment by jeffposnick** [comment]
This is covered by #53
