### ISSUE TITLE
Helpers for page navigation

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-testing-helpers#37]
In the course of writing tests for https://github.com/GoogleChrome/sw-helpers/pull/1, I found it necessary to script page navigations, running a set of tests before and after each navigation. I did this by "dropping down a level" and using the WebDriver directly to perform `.get(url1)`, then later `.get(url2)`, etc. This worked, but I wonder what folks think about providing a generic helper that could automate it a bit.

**Comment by gauntface** [comment]
I imagine in most cases you'd want to perform some kind of action / assertions between each navigation, if that's the case, I'm not sure you can slim down the webdriver code any more than it currently is.

Did you have something in mind?

**Comment by gauntface** [comment]
@jeffposnick please reopen this on selenium-assistant if you think it's still worth exploring.
