### ISSUE TITLE
Use node-geckodriver instead of shell script

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-testing-helpers#47]
@vladikoff just published https://github.com/vladikoff/node-geckodriver (thanks!), which allows you to fetch `geckodriver` as an `npm` dependency. We should use it in the same way we're using the [`chromedriver` module](https://github.com/GoogleChrome/sw-testing-helpers/blob/master/package.json#L23), and do away with [`get-marionette.sh`](https://github.com/GoogleChrome/sw-testing-helpers/blob/master/project/download/get-marionette.sh).

**Comment by vladikoff** [comment]
👀  👍

**Comment by gauntface** [comment]
+1 This is awesome!!! Will add it to [selenium-assistant](https://github.com/GoogleChrome/selenium-assistant) as well

**Comment by gauntface** [comment]
Moved here: https://github.com/GoogleChrome/selenium-assistant/issues/28
