### ISSUE TITLE
Move to selenium-webdriver 3.0 betas

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-testing-helpers#48]
Unfortunately, it looks like there is development being done in the 3.0 beta releases of `selenium-webdriver` that's needed for compatibility with Marionette. I'm running into this, in particular: https://github.com/SeleniumHQ/selenium/issues/2279

I need to call `driver.manage().timeouts().setScriptTimeout(TIMEOUT)` to make `driver.executeAsyncScript()` work properly, but that's broken when using Marionette + the `selenium-webdriver` 2.53.3 release.

**Comment by gauntface** [comment]
Are you happy with me moving this issue to selenium-assistant?

**Comment by jeffposnick** [comment]
Sure!

There's still a [dependency](https://github.com/GoogleChrome/sw-testing-helpers/blob/master/package.json#L28) in this project's `package.json` reading `"selenium-webdriver": "^2.53.2",`, so I assumed it was relevant here.

Should that dependency be removed from this project, and this project start depending on `selenium-assistant`?

**Comment by gauntface** [comment]
I have a PR to remove selenium assistant but I completely forgot about it,
re- reviewing it atm

**Comment by gauntface** [comment]
Moved on over to: https://github.com/GoogleChrome/selenium-assistant/issues/27
